routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Admin\BudgetController;


Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();

    Route::prefix('custom')
        ->name('custom.')
        ->group(function() {
            Route::resource('budgets', BudgetController::class);
        });
});


Route::get('/', 'Frontend\HomeController@index');
Route::get('/blogs', 'Frontend\BlogController@index');
Route::get('/gallery-detail','Frontend\GalleryController@index');

app/Models/Budget.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Budget extends Model
{
    use HasFactory;

    protected $fillable = [ 'project_id', 'type', 'currency_id', 'amount' ];

    public function project() {
        return $this->belongsTo(Project::class, 'project_id', 'id');
    }

    public function currency() {
        return $this->belongsTo(Currency::class, 'currency_id', 'id');
    }

    public function budget_details() {
        return $this->hasMany(BudgetDetail::class, 'budget_id', 'id');
    }

    public function getFmtCreatedAtAttribute($value)
    {
        return Carbon::parse($this->created_at)->format('d M, Y');
    }
}

app/Http/Controllers/Admin/BudgetController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\{Budget, BudgetDetail, Currency, Project};
use Illuminate\Http\Request;

class BudgetController extends Controller
{
    public function index()
    {
        return view('admin.budget.index')
            ->with('budgets', Budget::with(['project', 'currency', 'budget_details'])->paginate(20));
    }

    public function create()
    {
        return view('admin.budget.create')
            ->with('currencies', Currency::all())
            ->with('projects', Project::all());
    }


    public function store(Request $request)
    {
        $request->validate([
            'project_id' => 'required|unique:budgets',
            'type' => 'required',
            'amount' => 'required|integer|min:1',
            'start_date' => isset(request()->type) ? 'required|date' : '',
            'end_date' => isset(request()->type) ? 'required|date|after_or_equal:start_date' : '',
            'currency_id' => 'required',
        ],
        [
            'project_id.unique' => 'This project\'s budget has already created. Please update it or delete first to assign new one.',
        ]);

        $budget = new Budget();
        $budget->project_id = request()->project_id;
        $budget->type = request()->type;
        $budget->currency_id = request()->currency_id;
        $budget->amount = request()->amount;
        $budget->save();

        $this->saveOrUpdateBudgetDetails('store', request()->all(), $budget);

        return redirect()->route('custom.budgets.index')->with('message', 'New budget is successfully added against the project - ' . ucfirst($budget->project->name));

    }

    public function show($id)
    {
        //
    }

    public function edit(Budget $budget)
    {
        return view('admin.budget.edit')
            ->with('budget', $budget)
            ->with('currencies', Currency::all())
            ->with('projects', Project::all());
    }

    public function update(Budget $budget, Request $request)
    {
        $request->validate([
            'project_id' => 'required|unique:budgets,project_id,'.$budget->id,
            'type' => 'required',
            'amount' => 'required|integer|min:1',
            'start_date' => isset(request()->type) ? 'required|date' : '',
            'end_date' => isset(request()->type) ? 'required|date|after_or_equal:start_date' : '',
            'currency_id' => 'required',
        ],
        [
            'project_id.unique' => 'This project\'s budget has already created. Please update it or delete first to assign new one.',
        ]);

        $budget->project_id = request()->project_id;
        $budget->type = request()->type;
        $budget->currency_id = request()->currency_id;
        $budget->amount = request()->amount;
        $budget->save();

        $this->saveOrUpdateBudgetDetails('update', request()->all(), $budget);

        return redirect()->route('custom.budgets.index')->with('message', 'New budget is successfully updated against the project - ' . ucfirst($budget->project->name));
    }

    public function destroy($id)
    {
        //
    }

    public function saveOrUpdateBudgetDetails($action, $data, $budget) {
        if($action === 'store') {
            if(request()->type !== 'phase') {
                $budget->budget_details()->create([
                    'start_date' => request()->start_date,
                    'end_date' => request()->end_date
                ]);
            } else {
                $data = [];
                foreach(request()->start_date as $key => $stDate) {
                    $datum['budget_id'] = $budget->id;
                    $datum['start_date'] = $stDate;
                    $datum['end_date'] = request()->end_date[$key];
                    array_push($data, $datum);
                }
                BudgetDetail::insert($data);
            }
        } else {
            if(request()->type !== 'phase') {
                $budget->budget_details()->update([
                    'start_date' => request()->start_date,
                    'end_date' => request()->end_date
                ]);
            } else {
                $budget->budget_details()->delete();
                $data = [];
                foreach(request()->start_date as $key => $stDate) {
                    $datum['budget_id'] = $budget->id;
                    $datum['start_date'] = $stDate;
                    $datum['end_date'] = request()->end_date[$key];
                    array_push($data, $datum);
                }
                BudgetDetail::insert($data);
            }
        }
    }
}

resources/views/admin/budget/create.blade.php
@include('admin.includes.header')

<div class="container mt-5">
    @if (count($errors) > 0)
        <div class="alert alert-danger shadow round">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="row">
        <div class="col-md-12">
            <div class="d-flex justify-content-end mb-3">
                <a href="{{ route('custom.budgets.index') }}" class="btn btn-secondary shadow round">Back</a>
            </div>
        </div>
        <div class="col-md-12">
            <div class="card shadow round">
                <div class="card-header round">
                    <h5 class="card-title">Add New Budget</h5>
                </div>
                <div class="card-body">
                    <form action="{{ route('custom.budgets.store') }}" method="post">
                        @csrf
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="project_id">Project</label>
                                    <select id="project_id" name="project_id" class="form-control round">
                                        <option disabled selected>Choose an option</option>
                                        @if (count($projects) > 0)
                                            @foreach ($projects as $project)
                                                <option value="{{ $project->id }}"
                                                    {{ old('project_id') == $project->id ? 'selected' : '' }}>
                                                    {{ $project->name }}</option>
                                            @endforeach
                                        @endif
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6 type-div">
                                <div class="form-group">
                                    <label for="type">Type</label>
                                    <select id="type" name="type" class="form-control round">
                                        <option disabled selected>Choose an option</option>
                                        <option value="hourly" {{ old('type') == 'hourly' ? 'selected' : '' }}>
                                            Hourly</option>
                                        <option value="monthly" {{ old('type') == 'monthly' ? 'selected' : '' }}>
                                            Monthly</option>
                                        <option value="phase" {{ old('type') == 'phase' ? 'selected' : '' }}>
                                            Phase</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div id="static-field"></div>
                        <div id="dynamic-field"></div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="currency_id">Currency</label>
                                    <select id="currency_id" name="currency_id" class="form-control round">
                                        <option disabled selected>Choose an option</option>
                                        @if (count($currencies) > 0)
                                            @foreach ($currencies as $currency)
                                                <option value="{{ $currency->id }}"
                                                    {{ old('currency_id') == $currency->id ? 'selected' : '' }}>
                                                    {{ $currency->name }}
                                                    ({{ $currency->symbol }})
                                                </option>
                                            @endforeach
                                        @endif
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="amount">Amount</label>
                                    <input type="number" name="amount" class="form-control round" id="amount"
                                        value="{{ old('amount') }}">
                                </div>
                            </div>
                        </div>
                        <div class="card-footer d-flex justify-content-center">
                            <button type="submit" class="btn btn-secondary shadow round">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@include('admin.includes.footer')
<script>
    $(document).on('change', '[name="type"]', function() {
        $('#dynamic-field, #static-field').empty();
        if ($(this).val() === 'phase') {
            $('#dynamic-field').append(
                `<h6 class="text-secondary">Phase</h6><div class="phase-div">
                <ul class="list-group mb-3 round shadow"><li class="list-group-item"><div class="row mt-2">
                    <div class="col-md-5">
                        <div class="form-group">
                            <input type="date" name="start_date[]" class="form-control round start_date">
                        </div>
                    </div>
                    <div class="col-md-5">
                        <div class="form-group">
                            <input type="date" name="end_date[]" class="form-control round end_date">
                        </div>
                    </div>
                    <div class="col-md-2 add-btn-div">
                        <div class="form-group">
                            <button type="button" class="btn btn-md btn-secondary shadow round add-btn">+</button>
                        </div>
                    </div>
                    <div class="col-md-2 remove-btn"></div>
                </div></li></ul></div>`
            );

        } else {
            $('#static-field').append(
                `<div class="row default-dates-div">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="start_date">Start Date</label>
                        <input type="date" name="start_date"class="form-control round" id="start_date">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="end_date">End Date</label>
                        <input type="date" name="end_date" class="form-control round" id="end_date">
                    </div>
                </div>
            </div>`
            );
        }

    });

    $(document).on("click", '.add-btn', function() {
        let phaseDiv = $('.phase-div').eq(0).clone();
        phaseDiv = phaseDiv.find('.add-btn-div').remove().end();
        phaseDiv.addClass('newly-added').find('.remove-btn').append(`
            <div class="form-group">
                <button type="button" class="btn btn-md btn-danger shadow round">-</button>
            </div>
        `);
        const _input = phaseDiv.find('input');
        _input.attr({
            required: true
        }).val('');
        $('#dynamic-field').append(phaseDiv);
        _input.focus();
    });

    $(document).on('click', '.remove-btn button', () => $(event.target).parents('div.phase-div.newly-added').remove()
        .end());
</script>

resources/views/admin/budget/edit.blade.php
@include('admin.includes.header')

<div class="container mt-5">
    @if (count($errors) > 0)
        <div class="alert alert-danger shadow round">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="row">
        <div class="col-md-12">
            <div class="d-flex justify-content-end mb-3">
                <a href="{{ route('custom.budgets.index') }}" class="btn btn-secondary shadow round">Back</a>
            </div>
        </div>
        <div class="col-md-12">
            <div class="card shadow round">
                <div class="card-header round">
                    <h5 class="card-title">Update Budget</h5>
                </div>
                <div class="card-body">
                    <form action="{{ route('custom.budgets.update', $budget->id) }}" method="post">
                        @csrf
                        @method('PATCH')
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="project_id">Project</label>
                                    <select id="project_id" name="project_id" class="form-control round">
                                        <option disabled selected>Choose an option</option>
                                        @if (count($projects) > 0)
                                            @foreach ($projects as $project)
                                                <option value="{{ $project->id }}"
                                                    {{ $budget->project_id === $project->id ? 'selected' : '' }}>
                                                    {{ $project->name }}</option>
                                            @endforeach
                                        @endif
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6 type-div">
                                <div class="form-group">
                                    <label for="type">Type</label>
                                    <select id="type" name="type" class="form-control round">
                                        <option disabled selected>Choose an option</option>
                                        <option value="hourly" {{ $budget->type === 'hourly' ? 'selected' : '' }}>
                                            Hourly
                                        </option>
                                        <option value="monthly" {{ $budget->type === 'monthly' ? 'selected' : '' }}>
                                            Monthly</option>
                                        <option value="phase" {{ $budget->type === 'phase' ? 'selected' : '' }}>Phase
                                        </option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="for-edit-purpose">
                            @if ($budget->type !== 'phase')
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="start_date">Start Date</label>
                                            <input type="date" name="start_date"class="form-control round">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="end_date">End Date</label>
                                            <input type="date" name="end_date" class="form-control round">
                                        </div>
                                    </div>
                                </div>
                            @else
                                <h6 class="text-secondary">Phase</h6>
                                @for ($i = 0; $i < $budget->budget_details()->count(); $i++)
                                    <div class="phase-div">
                                        <ul class="list-group mb-3 round shadow">
                                            <li class="list-group-item">
                                                <div class="row mt-2">
                                                    <div class="col-md-5">
                                                        <div class="form-group">
                                                            <input type="date" name="start_date[]"
                                                                class="form-control round start_date">
                                                        </div>
                                                    </div>
                                                    <div class="col-md-5">
                                                        <div class="form-group">
                                                            <input type="date" name="end_date[]"
                                                                class="form-control round end_date">
                                                        </div>
                                                    </div>
                                                    <div class="col-md-2 add-btn-div {{ $i === 0 ? '' : 'd-none' }}">
                                                        <div class="form-group">
                                                            <button type="button"
                                                                class="btn btn-md btn-secondary shadow round add-btn">+</button>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-2 remove-btn {{ $i !== 0 ? '' : 'd-none' }}">
                                                        <div class="form-group">
                                                            <button type="button"
                                                                class="btn btn-md btn-danger shadow round">-</button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                @endfor
                            @endif
                        </div>
                        <div id="static-field"></div>
                        <div id="dynamic-field"></div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="currency_id">Currency</label>
                                    <select id="currency_id" name="currency_id" class="form-control round">
                                        <option disabled selected>Choose an option</option>
                                        @if (count($currencies) > 0)
                                            @foreach ($currencies as $currency)
                                                <option value="{{ $currency->id }}"
                                                    {{ $budget->currency_id === $currency->id ? 'selected' : '' }}>
                                                    {{ $currency->name }}
                                                    ({{ $currency->symbol }})
                                                </option>
                                            @endforeach
                                        @endif
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="amount">Amount</label>
                                    <input type="number" name="amount" class="form-control round" id="amount"
                                        value="{{ $budget->amount }}">
                                </div>
                            </div>
                        </div>
                        <div class="card-footer d-flex justify-content-center">
                            <button type="submit" class="btn btn-secondary shadow round">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@include('admin.includes.footer')
<script>
    $(document).on('change', '[name="type"]', function() {
        $('#dynamic-field, #static-field, .for-edit-purpose').empty();
        if ($(this).val() === 'phase') {
            $('#dynamic-field').append(
                `<h6 class="text-secondary">Phase</h6><div class="phase-div">
                <ul class="list-group mb-3 round shadow"><li class="list-group-item"><div class="row mt-2">
                    <div class="col-md-5">
                        <div class="form-group">
                            <input type="date" name="start_date[]" class="form-control round start_date">
                        </div>
                    </div>
                    <div class="col-md-5">
                        <div class="form-group">
                            <input type="date" name="end_date[]" class="form-control round end_date">
                        </div>
                    </div>
                    <div class="col-md-2 add-btn-div">
                        <div class="form-group">
                            <button type="button" class="btn btn-md btn-secondary shadow round add-btn">+</button>
                        </div>
                    </div>
                    <div class="col-md-2 remove-btn d-none">
                        <div class="form-group">
                            <button type="button"
                                class="btn btn-md btn-danger shadow round">-</button>
                        </div>
                    </div>
                </div></li></ul></div>`
            );

        } else {
            $('#static-field').append(
                `<div class="row default-dates-div">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="start_date">Start Date</label>
                        <input type="date" name="start_date"class="form-control round" id="start_date">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="end_date">End Date</label>
                        <input type="date" name="end_date" class="form-control round" id="end_date">
                    </div>
                </div>
            </div>`
            );
        }

    });

    $(document).on("click", '.add-btn', function() {
        let phaseDiv = $('.phase-div').eq(0).clone();
        phaseDiv = phaseDiv.find('.add-btn-div').remove().end();
        phaseDiv.find('.remove-btn').removeClass('d-none');
        const _input = phaseDiv.find('input');
        _input.attr({
            required: true
        }).val('');
        $('#dynamic-field').append(phaseDiv);
        _input.focus();
    });

    $(document).on('click', '.remove-btn button', () => $(event.target).parents('div.phase-div').remove()
        .end());
</script>

resources/views/admin/budget/index.blade.php
@include('admin.includes.header')

<div class="container mt-5">
    @if (session()->has('message'))
        <div class="alert alert-success round shadow">
            {{ session()->get('message') }}
        </div>
    @endif
    <div class="row">
        <div class="col-md-12">
            <div class="d-flex justify-content-end mb-3">
                <a href="{{ route('custom.budgets.create') }}" class="btn btn-secondary shadow round">Add New Budget</a>
            </div>
        </div>
        <div class="col-md-12">
            <div class="card round shadow">
                <div class="card-header">
                    <h5 class="card-title">Budget Listing</h5>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">No.</th>
                                    <th scope="col">Date</th>
                                    <th scope="col">Project</th>
                                    <th scope="col">Type</th>
                                    <th scope="col">Amount</th>
                                    <th scope="col">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($budgets as $budget)
                                    <tr>
                                        <th scope="row">{{ $loop->iteration }}</th>
                                        <td>{{ $budget->fmt_created_at }}</td>
                                        <td>{{ $budget->project->name }}</td>
                                        <td>{{ ucfirst($budget->type) }}</td>
                                        <td>{{ $budget->currency->symbol }}{{ $budget->amount }}</td>
                                        <td>
                                            <a href="{{ route('custom.budgets.show', $budget->id) }}"
                                                class="text-secondary text-decoration-none">View</a> |
                                            <a href="{{ route('custom.budgets.edit', $budget->id) }}"
                                                class="text-secondary text-decoration-none">Edit</a> |
                                            <a href="javascript:void(0)"
                                                class="text-secondary text-decoration-none">Delete</a> |
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <th colspan="7" class="text-center">No record found.</th>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
                @if ($budgets->count() > 0)
                    <div class="card-footer">
                        {{ $budgets->links() }}
                    </div>
                @endif
            </div>
        </div>
    </div>
</div>

@include('admin.includes.footer')